declare module "openai"
declare module "google-auth-library"
declare module "crypto"
declare module "googleapis"
declare module "react-spinners"
declare module "react-google-button"
declare module "*.png"
